image: docker:latest

services:
- docker:dind

stages:
- build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  only:
  - tags
  script:
  - docker build -t $IMAGE_TAG .
  - docker tag $IMAGE_TAG $LATEST_TAG
  - docker push $IMAGE_TAG
  - docker push $LATEST_TAG
